### ISSUE TITLE
 runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by Joly0** [lkarlslund/Adalanche#31]
Hey, i ran ".\adalanche-windows-x64-v2024.1.11-4-g69a66ad.exe analyze" and used the default query. 
I can get data for various users when clicking on their node, but for some, i dont get any information and only see this:
![image](https://github.com/lkarlslund/Adalanche/assets/13993216/6df6a1a9-f3d2-478d-99f3-5b8058b49b88)

also in the terminal i can see this error message:
```
2024/01/26 15:03:58 http: panic serving 127.0.0.1:55950: runtime error: slice bounds out of range [:256] with length 150
goroutine 1100 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:1868 +0xb9
panic({0xa1b720?, 0xc000ca6000?})
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x270
github.com/lkarlslund/adalanche/modules/analyze.analysisfuncs.func3.1(0x8570?, {0x1b50710?, 0xc003930760?})
        /home/runner/work/Adalanche/Adalanche/modules/analyze/webservicefuncs.go:149 +0x1fa
github.com/lkarlslund/adalanche/modules/analyze.analysisfuncs.func3.(*Object).AttrIterator.(*AttributeValueMap).Iterate.func2({0x3880?, {0x1b50710?, 0xc003930760?}})
        /home/runner/work/Adalanche/Adalanche/modules/engine/attributevaluemap.go:82 +0x22
github.com/lkarlslund/gonk.(*Gonk[...]).Range(0xa727d5?, 0xc000345930?)
        /home/runner/go/pkg/mod/github.com/lkarlslund/gonk@v0.0.0-20231113084556-53a1781342e9/gonk.go:103 +0x95
github.com/lkarlslund/adalanche/modules/engine.(*AttributeValueMap).Iterate(...)
        /home/runner/work/Adalanche/Adalanche/modules/engine/attributevaluemap.go:81
github.com/lkarlslund/adalanche/modules/engine.(*Object).AttrIterator(...)
        /home/runner/work/Adalanche/Adalanche/modules/engine/object.go:1097
github.com/lkarlslund/adalanche/modules/analyze.analysisfuncs.func3({0x1b4e600, 0xc003e30620}, 0xc0045084e0?)
        /home/runner/work/Adalanche/Adalanche/modules/analyze/webservicefuncs.go:142 +0x5c5
net/http.HandlerFunc.ServeHTTP(0xc004672400?, {0x1b4e600?, 0xc003e30620?}, 0x19edd9efb08?)
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0005963c0, {0x1b4e600, 0xc003e30620}, 0xc004672300)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5
net/http.serverHandler.ServeHTTP({0xc004508390?}, {0x1b4e600?, 0xc003e30620?}, 0x6?)
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000f46360, {0x1b50908, 0xc0057201b0})
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 197
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:3086 +0x5cb
```

**Comment by lkarlslund** [comment]
It is fixed in the latest build already

**Comment by Joly0** [comment]
Yep, can confirm its fixed
